# Generated by Django 5.1.6 on 2025-03-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_order_shipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
